spring.application.name=piedrazul

spring.datasource.url=jdbc:postgresql://localhost:5432/piedrazuldb
spring.datasource.username=piedrazul_admin
spring.datasource.password=Piedrazul123.

spring.jpa.properties.hibernate.default_schema=piedrazul
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.port=8080